### ISSUE TITLE
自动生成演示_住宅行列式+点式

### ISSUE THREAD

**Issue by Fengweijia-prog** [MetaCityGenerator/MetaCityGenerator_GHComponent#1]
“自动生成演示_住宅行列式+点式” 没有找到对应的文件，请问可否提供或者在哪里可以找到呢？

**Comment by alphonse-lin** [comment]
您好，我在food4rhino有给您回复...因为住宅行列式的话，直接调整用地属性的输入就可以了。比如把用地属性调为R（或者0），就是居住了。
![image](https://github.com/MetaCityGenerator/MetaCityGenerator_GHComponent/assets/38575020/91a88948-93ec-43d8-8ff0-ad19b08daa4c)
